-- TABLO OLUÞTURMA ÝÞLEMLERÝNDE ÝLERÝDEKÝ SAFHALARDA DA KULLANMAK ÝÇÝN HR (ÝNSAN KAYNAKLARI) MODELÝ TABLOLARI OLUÞTURUKACAKTIR.

-- BÖLGE TABLOSU OLUÞTURMA.
CREATE TABLE REGIONS(
       REGION_ID NUMBER,
       REGION_NAME VARCHAR2(25)
);

-- ÜLKELER TABLOSU OLUÞTURMA.
CREATE TABLE COUNTRIES(
       COUNTRY_ID CHAR(2),
       COUNTRY_NAME VARCHAR2(40),
       REGION_ID NUMBER -- TABLOLAR ARASI ÝLÝÞKÝ KURMAK ÝÇÝN.
);

-- LOKASYONLAR TABLOSU OLUÞTURMA.
CREATE TABLE LOCATIONS(
       LOCATION_ID NUMBER(4),
       STREET_ADDRESS VARCHAR2(40),
       POSTAL_CODE VARCHAR2(12),
       CITY VARCHAR2(30) NOT NULL, -- BOÞ GEÇÝLEMEZ.
       STATE_PROVINCE VARCHAR2(25),
       COUNTRY_ID CHAR(2) -- TABLOLAR ARASI ÝLÝÞKÝ KURMAK ÝÇÝN.
);

-- BÖLÜMLER TABLOSU OLUÞTURMA.
CREATE TABLE DEPARTMENTS(
       DEPARTMENT_ID NUMBER(2),
       DEPARTMENT_NAME VARCHAR2(30),
       MANAGER_ID NUMBER(4),
       LOCATION_ID NUMBER(4)
);

-- ÜNVAN TABLOSU OLUÞTURMA.
CREATE TABLE JOBS(
       JOB_ID VARCHAR2(10),
       JOB_TITLE VARCHAR2(35) NOT NULL, -- BOÞ GEÇÝLEMEZ.
       MIN_SALARY NUMBER(6),
       MAX_SALARY NUMBER(6)
);

-- ÇALIÞANLAR TABLOSU OLUÞTURMA.
CREATE TABLE EMPLOYEES(
       EMPLOYEE_ID NUMBER(6),
       FIRST_NAME VARCHAR2(20),
       LAST_NAME VARCHAR2(25),
       EMAIL VARCHAR2(25) NOT NULL, -- BOÞ GEÇÝLEMEZ.
       PHONE_NUMBER VARCHAR2(20),
       HIRE_DATE DATE NOT NULL, -- BOÞ GEÇÝLEMEZ.
       JOB_ID VARCHAR2(10), -- TABLOLAR ARASI ÝLÝÞKÝ KURMAK ÝÇÝN.
       SALARY NUMBER(8,2),
       COMISSION_PCT NUMBER(2,2),
       MANAGER_ID NUMBER(4), -- TABLOLAR ARASI ÝLÝÞKÝ KURMAK ÝÇÝN.
       DEPARTMENT_ID NUMBER(4),
       
       -- MAAÞ KOLONUNA NEGATÝF DEÐER GÝRÝLEMESÝN.
       CONSTRAINT emp_salary_min CHECK(SALARY > 0),
       -- MAÝL ADRESLERÝ TEKÝL YANÝ UNIQUE OLSUN.
       CONSTRAINT emp_email_uk UNIQUE(EMAIL)
);

-- ÇALIÞANLARIN TARÝH TABLOSUNU OLUÞTURMA.
CREATE TABLE JOB_HISTORY(
       EMPLOYYE_ID NUMBER(6), -- TABLOLAR ARASI ÝLÝÞKÝ KURMAK ÝÇÝN.
       START_DATE DATE NOT NULL, -- BOÞ GEÇÝLEMEZ.
       END_DATE DATE NOT NULL, -- BOÞ GEÇÝLEMEZ.
       JOB_ID VARCHAR2(10), -- TABLOLAR ARASI ÝLÝÞKÝ KURMAK ÝÇÝN.
       DEPARTMENT_ID NUMBER(4), -- TABLOLAR ARASI ÝLÝÞKÝ KURMAK ÝÇÝN.
       
       -- ÝÞE BAÞLAMA TARÝHÝ BÝTME TARÝHÝNDEN BÜYÜK OLMAMALI.
       CONSTRAINT jhist_date_interval CHECK (END_DATE > START_DATE)
);
