-- JOINS
-- CROSS JOIN - KARTEZYEN ÇARPPIM DEMEK S(A) = N, S(B) = M ÝSE S(AXB) = N*M

-- KLASÝK FORMAT
SELECT LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS;

-- ANSI FORMAT
SELECT LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS;
