-- TEST ADINDA VE ÞÝFRESÝ TEST OLAN BÝR KULLANICI OLUÞTURULACAK. 
-- VARSAYILAN TABLESPACE'SÝ USERS, GECÝCÝ TABLESPACE'SÝ TEMP OLACAK.
-- OLUÞTURULAN KULLANICI HESABINA ÝLK GÝRÝÞ YAPARKEN ÞÝDRESÝNÝ DEÐÝÞTÝRECEK.
-- KULLANICININ KÝLÝDÝ KAPALI OLACAK.
CREATE USER TEST IDENTIFIED BY TEST
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PASSWORD EXPIRE
ACCOUNT LOCK
;

-- TEST KULLANICISININ KÝLÝDÝ AÇILDI.
ALTER USER TEST ACCOUNT UNLOCK;

-- TEST KULLANICISINA VERÝTABANINA BAÐLLANMA YETKÝSÝ VERME.
GRANT CONNECT TO TEST;

-- TEST KULLANICISINA KAYNAK KULLANMA VE DBA YETKÝSÝ VERME.
GRANT RESOURCE, DBA TO TEST;

-- TEST KULLANICISINDAN VERÝTABANINA BAÐLANMA YETKÝSÝNÝ GERÝ ALMA.
REVOKE CONNECT FROM TEST;

-- TEST KULLANICISINDAN KAYNAK KULLANMA VE DBA YETKÝSÝNÝ GERÝ ALMA.
REVOKE RESOURCE, DBA FROM TEST;

-- TEST KULLANICISINI SÝLME.
DROP USER TEST CASCADE;
