-- DATA CONTROL LANGUAGE
-- GRANT AND REVOKE STATEMENT

-- TEST KULLANICISI, HOST KULLANICISINA REGIONS TABLOSU ÜZERÝNDE SORGU YAPMA YETKÝSÝ VERSÝN.
GRANT SELECT ON REGIONS TO HOST;

-- TEST KULLANICISI,HOST KULLANICISA REGIONS TABLOSU ÜZERÝNDE UPDATE YETKÝSÝ VERSÝN FAKAT HOST KULLANICISI BU YETKÝYÝ DEVREDEBÝLSÝN.
GRANT UPDATE ON REGIONS TO HOST WITH GRANT OPTION;

-- TEST KULLANICISI, HOST KULLANICISINA REGIONS TABLOSU ÜZERÝNDE INSERT YAPMA YETKÝSÝ VERSÝN.
GRANT INSERT ON REGIONS TO HOST;

-- TEST KULLANICIS VERÝTABANINA BAÐLANAN TÜM KULLANICILARA REGIONS TABLOSU ÜZERÝNDE SORGU YETSKÝSÝ VERSÝN.
GRANT SELECT ON REGIONS PUBLIC;

-- TEST KULLANICISI VERDÝÐÝ YETKÝLERÝ SIRASIYLE GERÝ ALSIN.
REVOKE SELECT ON REGIONS FROM HOST;
REVOKE INSERT ON REGIONS FROM HOST;
