-- DATA MANIPULATION LANGUAGE
-- SELECT STATEMENT
-- SELECT SELECT_LIST FROM SOURCE_LIST WHERE ORDER BY HAVING;

-- EMPLOYEES TABLOSUNDAKÝ TÜM VERÝLERÝ LÝSTELEMEK.
SELECT * FROM EMPLOYEES;

-- EMPLOYEES TABLOSUNDAN SADECE FIRST NAME, LAST NAME VE E MAIL KOLANLARINI LÝSTELEMEK.
SELECT FIRST_NAME, LAST_NAME, EMAIL FROM EMPLOYEES;

-- EMPLOYEES TABLOSUNDAKÝ MANGER ID KOLONUNU EKRANA YAZDIRIRKEN KOLON ADINI "M", FIRST NAME KOLONUNU ÝSE "ADI" OLARAK YAZDIRSIN.
SELECT MANAGER_ID M, FIRST_NAME ADI FROM EMPLOYEES;

-- EMPLOYEES TABLOSUNDAKÝ FIRST NAME VE EMAIL KOLONLARININ ÝSÝMLERÝNÝ SIRAYIYLA "ILK ADI", "E POSTA" OLARAK EKRANA YAZDIRSIN.
SELECT FÝRST_NAME "ILK ADI", EMAIL "E POSTA" FROM EMPLOYEES;

-- 90 NOLU DEPARTMANDA BULUNANLARI LÝSTELESÝN.
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;

-- 90 VEYA 100 NOLU DEPARTMANDA BULUNANLARI LÝSTELESÝN.
SELECT * FROM EMPLOYEES WHERE DEPARMENT_ID IN (90,100);
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_IS = 90 OR DEPARTMENT_ID = 100;

-- LAST NAME'ÝN BAÞINDA M HARFÝ BULUNANLARI LÝSTELESÝN.
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE 'M%';

-- LAST NAME'IN ORTASINDA M HARFÝ GEÇENLERÝ LÝSTELESÝN.
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%M%';

-- LAST NAME'ÝN ÝKÝNCÝ KARAKTERÝ A VE DÖRDÜNCÜ KARAKTERÝ E OLANLARI LÝSTELESÝN.
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '_A_E%';

-- MAAÞI 1000'DEN BÜYÜK OLANLARI VE KOMÝSYON ORANLARI BOÞ OLMAYANLARI LÝSTELESÝN.
SELECT * FROM EMPLOYEES WHERE SALARY > 1000 AND COMISSION IS NOT NULL;

-- DEPARTMENT_ID KOLONUNA GÖRE SIRALASIN.
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID;

-- DEPARTMENT_ID KOLONUNA GÖRE AZALAN, MAAÞ KOLONUNA GÖRE ARTAN BÝÇÝMDE SIRALASIN.
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID DESC, SALARY ASC;

-- FIRST_NAME KOLONUNA GÖRE ARTAN, LAST_NAME KOLONUNA GÖRE AZALAN BÝÇÝMDE SIRALASIN.
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES ORDER BY 1 ASC, 2 DESC;

-- DEPARTMENT_ID'SÝ 90 OLANLARI MAAÞINA GÖRE AZALAN BÝÇÝMDE SIRALASIN.
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 90 ORDER BY SALARY DESC; 
