-- DATA MANIPULATION LANGUAGE
-- SELECT HIERARCHICAL QUERIES

-- ÇALIÞANLAR ÝLE YÖNETÝCÝLER ARASI HÝYERARÞÝK ÝLÝÞKÝ.
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID FROM EMPLOYEES CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

-- ÇALIÞANLAR ÝLE YÖNETÝCÝLER ARASI HÝYERARÞÝK ÝLÝÞKÝ - SEVÝYE NO, ÇALIÞAN LEVEL.
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID LEVEL FROM EMPLOYEES CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID LEVEL FROM EMPLOYEES START WITH EMPLOYEE_ID = 100 CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID ORDER SIBLINGS BY LAST_NAME;
-- HÝYERARÞÝYÝ BELLÝ SIRADAN BAÞLATAÝLÝRÝZ. AYRICA HÝYERARÞÝK SIRADA SIRALAYABÝLÝRÝZ.
-- LEVEL-1 ÞEKLÝNDE YAZARSAK EN ÜSTTEKÝ KÝÞÝDE LÝSTELENMÝÞ OLUR.

SELECT LAST_NAME CALISAN, CONNECT_BY_ROOT LAST_NAME YONETICI, LEVEL-1 SEVIYE, SYS_CONNECT_BY_PATH(LAST_NAME, '->') PATH FROM EMPLOYEES WHERE DEPARTMENT_ID = 100 AND LAVEL>1 CONNECT BY PRIOR EMPLOYEE_ID = DEPARTMENT_ID;
-- HÝYERARÞÝDEKÝ DÜZENÝ ÇIKARMAK ÝSTÝYORSAK: SYS_CONNECT_BY_PATH KOMUTU KULLANILIR.
-- N ÜST SEVÝYEDEKÝ YÖNETÝCÝNÝN ADINI YANINA YAZSIN ÝSTÝYORSAK: CONNECT_BY_ROOT KOMUTU KULLANILIR.
