-- JOINS
-- FULL JOIN 

-- ANSI FORMAT
SELECT E.LAST_NAME, E.DEPARMETN_ID, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E FULL JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
FULL JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;
