-- FUNCTIONS (FONKSÝYONLAR)
-- SAYISAL, KARAKTER, TEKÝL SONUÇ, ÝSTATÝKSEL, TARÝH VE ZAMAN, ...

-----------------------------------------------------------------------------
-- SAYISAL FONKSÝYONLAR

-- SIGN, ÝÇÝNDEKÝ SAYIYA BAKAR VE -1 VEYA +1 DÖNDÜRÜR.
SELECT SIGN(-3) FROM DUAL;
-- ABS, MUTLAK DEÐER ALIR.
SELECT ABS(-5) FROM DUAL;
SELECT SIGN(-5*3-1), ABS(-4*8) FROM DUAL;
-- TRÝGONÝMETRÝK, DERECEYÝ RADYANA DÖNÜÞTÜR. DERECE*PÝ/180
SELECT COS(30 *(22/7)/180) FROM DUAL;
SELECT SIN(30* (22/7)*180) FROM DUAL;
SELECT COS(0) FROM DUAL;
SELECT SIN(0) FROM DUAL;
-- CEIL, ÜSTE YUVARLA.
SELECT Ceil(123.456) FROM DUAL;
-- FLOOR, ALTA YUVARLAMA.
SELECT FLOOR(123.456) FROM DUAL;
-- EXP, E SAYISIDIR. E ÜZERÝ ANLAMINA GELÝR.
SELECT EXP(1)FROM DUAL;
-- LN, LOGARÝTMADIR.
SELECT LN(1) FROM DUAL;
SELECT LN(EXP(1)) FROM DUAL;
-- LOG, ÝKÝ SAYI ALIR. TABAN VE ÜS.
SELECT LOG(5,25) FROM DUAL;
-- MOD, SAYININ MODUNU ALIR.
SELECT MOD(10,3) FROM DUAL;
SELECT LEVEL, MOD(100,LEVEL) FROM DUAL CONNECT BY LEVEL < 12;
-- POWER, ÜS ALIR.
SELECT POWER(5,2) FROM DUAL;
-- SQRT, KARAKÖK ALIR.
SELECT SQRT(25) FROM DUAL;

-----------------------------------------------------------------------------
-- KARAKTER FONKSÝYONLAR

-- LOWER, STRÝNGÝ KÜÇÜK HARFE CEVÝRÝR.
SELECT LOWER('DEpARMENt') FROM DUAL;
-- UPPER, STRÝNGÝ BÜYÜK HARFE ÇEVÝRÝR.
SELECT UPPER('DEpARMENt') FROM DUAL;
--INITCAP, BAÞ HARFLERÝ BÜYÜK YAPAR.
SELECT INITCAP('dEpARMENt') FROM DUAL;
-- SUBSTRING, KARAKTER DÝZÝSÝ KESME.
SELECT Substr('ANKARA-KARS', 5, 5) FROM DUAL;
-- LENGTH, UZUNLUK VERÝR.
SELECT LENGTH('ANKARA-KARS') FROM DUAL;
-- INSTR, POZÝSYON VERÝR.
SELECT INSTR('ADIGUZEL', 'I') FROM DUAL;
-- REPLACE, KELÝME DEÐÝÞTÝRME.
SELECT REPLACE('ANKARA-KARS','RA-KA','AAAA') FROM DUAL;
-- TRANSLATE, REPLACEDEN FARKI HARF HARF ÇALIÞMASI.
SELECT TRANSLATE('ORACLE SQL', 'ROAS', '1234') FROM DUAL;
-- RPAD, 20 KARKTERDEN AZ OLANLARO * ÝLE DOLDUR.
SELECT RPAD('ADADASSAADAD', 20, '*') FROM DUAL;
-- LPAD, 20 KARAKTERDEN AZ OLANLARI SOLDAN TAMAMLA.
SELECT LPAD('ADADASSAADAD', 20, '*') FROM DUAL;
-- LTRIM, ÝFADENÝN SOLUNDAKÝ BOÞLUKLARI TEMÝZLE.
SELECT LTRIM('        ORACLE SQL        ') FROM DUAL;
-- RTRIM, ÝFADENÝN SAÐINDAKÝ BOÞLUKLARI TEMÝZLE.
SELECT RTRIM('        ORACLE SQL        ') FROM DUAL;
-- TRIM, HEM SAÐ HEM DE SOLDAKÝ BOÞLUKLARI TEMÝZLE.
SELECT TRIM('        ORACLE SQL        ') FROM DUAL;
-- CONCAT, STRING BÝRLEÞTÝRME.
SELECT CONCAT('QEQWEQWQWWQQ', 'ASDADSASDADS') FROM DUAL;
SELECT CONCAT(CONCAT('QEQWEQWQWWQQ', 'ASDADSASDADS'), 'HKHKHKHKHKHKHK') FROM DUAL;
-- ||, ÝFADE BÝRÞLEÞTÝRME.
SELECT 'KARS' || ' ' || 'ANKARA' "KARS ANKARA" FROM DUAL;

-----------------------------------------------------------------------------
-- ÝSTATÝKSEL FONKSÝYONLAR

-- AVG, ORTALAMA ALIR.
SELECT AVG(SALARY) FROM EMPLOYEES;
-- MAX, EN BÜYÜK DEÐER.
-- MÝN, EN KÜÇÜK DEÐER.
-- SUM, TOPLAM.
-- COUNT, SAYI VERÝR.
-- STDDEV, STANDART SAPMA VERÝR.
-- VARIANCE, VARYANS HESAPLAR.








