-- JOINS
-- INNER JOIN - KESÝÞÝM

-- KLASÝK FORMAT
SELECT E.LAST_NAME, E.DEPARMETN_ID, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID;


-- ANSI FORMAT
SELECT E.LAST_NAME, E.DEPARMETN_ID, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
ORDER BY E.LAST_NAME;
