-- JOINS
-- NATURAL JOIN

-- ÝKÝ TABLO ARASINDA AYNI ÝSEM SAHÝP KOLONLAR OLMALI. KOLONLARIN DEÐERLERÝ EÞÝT OLANLARI LÝSTELER. AYNI FAKAT VERÝ TÜRÜ FARKLIYSA SORGU ÇALIÞMAZ.
SELECT * FROM EMPLOYEES NATURAL JOIN EMPLOYEES_COPY;
