-- ROLES

-- TEST KULLANICISI ÝKÝ TANE ROL TANIMLIYOR.
CREATE ROLE R_SELUPT;
CREATE ROLE R_INSDEL;

-- TEST KULLANICISI TANIMLAMIÞ OLDUÐU ÝKÝ ROLE DE FARKLI ÖZELLÝKLER ATASIN FAKAT ÖZELLÝKLER SADECE REGIONS TABLOSUNDA ÝÞLEM GÖRSÜN.
GRANT SELECT, UPDATE ON REGIONS TO R_SELUPT;
GRANT INSERT, DELETE ON REGIONS TO R_INSDEL;

-- TEST KULLANICISININ OLUÞTURMUÞ OLDUÐU ROLLERÝ KULLANICILARA ATASIN.
GRANT R_SELUPT TO BILGE;
GRANT R_INSDEL TO CELEBI;

-- ROLE SAHÝP OLAN KULLANICILAR AÞAÐIDAKÝ SÖZDÝZÝMÝNÝ ÇALIÞTIRARAK YETKÝ SAHÝBÝ OLABÝLÝRLER.
SET ROLE R_INSDEL;
SET ROLE R_SELUPT;

-- TEST KULLANICISI UPDATE ROLÜNÜ GERÝ ÇEKSÝN.
REVOKE UPDATE ON REGIONS FROM R_SELUPT; -- SELECT ROLÜ TEK KALMIÞ OLDU.
