-- SET OPERATORS (KÜME OPERATÖRLERÝ)
-- UNION - BÝRLEÞÝM || INTERSECT - KESÝÞÝM || MINUS - FARK

-- DEPARTMAN TABLOSUNDAN KAYIT NUMARASI 160 VE ALTINI DEPT1 TABLOSUNA ATALIM.
CREATE TABLE DEPT1 AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID <= 160;

-- DEPARTMAN TABLOSUNDAN KAYIT NUMARASI 100 VE ÜSTÜNÜ DEPT2 TABLOSUNA ATALIM.
CREATE TABLE DEPT2 AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID >= 100;

-- DEPT1 VE DEPT2 TABLOLARININ BÝRLEÞÝMLERÝNÝ ALALIM FAKAT TEKRAR EDEN KAYITLAR BÝR KERE YAZILSIN.
SELECT * FROM DEPT1 UNION SELECT * FROM DEPT2;

-- DEPT1 VE DEPT2 TABLOSUNUN BÝRLEÞÝMÝNÝ ALALIM FAKAT TÜM VERÝLER EKRANA YAZILSIN.
SELECT *FROM DEPT1 UNION ALL SELECT * FROM DEPT2;

-- DEPT1 VE DEPT2 TABLOLARININ KESÝÞÝMLERÝNÝ BULALIM.
SELECT * FROM DEPT1 INTERSECT SELECT * FROM DEPT2;

-- DEP1 TABLOSUNDA OLUP DEPT2 TABLOSUNDA OLMAYAN VERÝLERÝ EKRANA YAZALIM.
SELECT * FROM DEPT1 MINUS SELECT * FROM DEPT2;

-- DEPT2 TABLOSUNDA OLUP DEPT1 TABLOSUNDA OLMAYAN VERÝLERÝ EKRANA YAZALIM.
SELECT * FROM DEPT2 MINUS SELECT * FROM DEPT1;

-- NOT: * DEYÝMÝ YERÝNE KOLON ADI GÝRECEKSEK HER ÝKÝ TABLOYADA AYNI KOLON ADLARI GÝRÝLMEK ZORUNDADIR VE KOLONLARIN VERÝ TÝPLERÝ DE AYNI OLMAK ZORUNDADIR.
